Normalization:

In [112]:
import numpy as np

X = np.random.rand(5,5)

mean = X.mean()
std = X.std()
normalized = (X - mean) /std

np.save('X_normalized.npy', normalized)

print("Variables: \n", X)
print("\nNormalized: \n", X_normalized)

Variables: 
 [[0.71415375 0.71016089 0.31247838 0.8471886  0.71315481]
 [0.16781366 0.76765762 0.50231176 0.90438585 0.21104625]
 [0.86661248 0.05839994 0.00457689 0.26394781 0.24855211]
 [0.49831513 0.90546986 0.4992076  0.01404377 0.79460372]
 [0.24001054 0.97320465 0.11697957 0.09679297 0.76263597]]

Normalized: 
 [[-0.53918739 -1.12477413 -1.23686687  0.57827219 -1.3611832 ]
 [ 0.10769153  0.68750757  0.92539103  0.10801272 -0.13336823]
 [ 0.24334409  0.17824272  1.30087428 -0.80097859 -1.15108963]
 [-1.66822466  0.90399064  1.43357832  0.9132025   0.80702661]
 [-1.49841158  1.59486616  0.9982024   0.03022021 -1.2963387 ]]


Divisible by 3 Problem:

In [126]:
import numpy as np

n = np.arange(1, 101)
squares = n ** 2
a = squares.reshape(10, 10)

divisible_by_3 = s[s % 3 == 0]

np.save('div_by_3.npy', divisible_by_3)

print("10x10 array: \n", a) 
print("\nNumbers Divisible by 3: ")
np.load('div_by_3.npy')

10x10 array: 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Numbers Divisible by 3: 


array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])